### PR TITLE
cutlass update

### PR DESCRIPTION
**Pull request by Shreya-gaur**

### CODE REVIEW

**Review by JRPan — APPROVED** [review]
Looks good

**Comment by macto94** [comment]
when I run `./util/tracer_nvbit/run_hw_trace.py -B cutlass_5_trace -D 0` 
it says `FileNotFoundError: [Errno 2] No such file or directory: '/root/accel-sim-framework/gpu-app-collection/src/..//bin/11.4/release/cutlass_profiler'`

it seems that cutlass_profiler is not linked properly. 
maybe, should I change 'cutlass_profiler' to 'cutlass_perf_test_k1' in "util/job_launching/apps/define-all-apps.yml" ?
or change 'gpu-app-collection/src/Makefile' to include 'make cutlass_profiler -j12'?

**Comment by JRPan** [comment]
Did you pull latest gpu-app-collection? 
Cutlass is included in this commit https://github.com/accel-sim/gpu-app-collection/pull/18

**Comment by macto94** [comment]
@JRPan Yes, I pull latest dev branch. (both accel-sim and gpu-app-collection.)

**Comment by JRPan** [comment]
@Shreya-gaur

**Comment by macto94** [comment]
Temporarily, I modified the [cutlass part of the "gpu-app-collection/src/Makefile"](https://github.com/accel-sim/gpu-app-collection/blob/63f97ac0c6eaa8be444973b3fc340aaeeaefe2f2/src/Makefile#L427-L437) as follows, but it needs to be verified.

```
cutlass:
        mkdir -p $(BINDIR)/$(BINSUBDIR)/
        echo $(BINDIR)
        git submodule init && git submodule update
        #$(SETENV) mkdir -p cuda/cutlass-bench/build && cd cuda/cutlass-bench/build && cmake .. -DUSE_GPGPUSIM=1 -DCUTLASS_NVCC_ARCHS=70 && make cutlass_profiler -j12
        $(SETENV) mkdir -p cuda/cutlass-bench/build && cd cuda/cutlass-bench/build && cmake .. -DUSE_GPGPUSIM=1 -DCUTLASS_NVCC_ARCHS=80 && make cutlass_profiler -j12
#       cd cuda/cutlass-bench/build/tools/profiler && ln -s -f ../../../../binary.sh . && ./binary.sh
        echo $(BINDIR)
        cp cuda/cutlass-bench/build/tools/profiler/cutlass_profiler $(BINDIR)/$(BINSUBDIR)/

# I was unsure of the role of k2 and k3, so I removed them for now.
#        cp $(BINDIR)/$(BINSUBDIR)/cutlass_perf_test_k1 $(BINDIR)/$(BINSUBDIR)/cutlass_perf_test_k2
#        cp $(BINDIR)/$(BINSUBDIR)/cutlass_perf_test_k1 $(BINDIR)/$(BINSUBDIR)/cutlass_perf_test_k3
```

but, when I try to simulate the traces of wmma-gemm with generated A100 config, "Segmentation fault" is raised. 
I only change the args of "define-all-apps.yml"
```
cutlass_5_trace:
    exec_dir: "$GPUAPPS_ROOT/bin/$CUDA_VERSION/release/"
    data_dirs: "$GPUAPPS_ROOT/data_dirs/"
    execs:
        - cutlass_profiler:
            - args: --seed=2020 --dist=0 --operation=gemm --m=512 --n=512 --k=512 --accum=f32 --stages=4 --op_class=tensorop --iterations=1 --provider=cutlass
              accel-sim-mem: 3G
```

**Comment by JRPan** [comment]
Thanks I'll check that.

**Pull request merged**
