### PR TITLE
Nvbit 1.7

### PR DESCRIPTION
**Pull request by barnes88**
update tracer tool to use nvbit 1.7

### CODE REVIEW

**Comment by JRPan** [comment]
Wow you are fast

**Review by christindbose — DISMISSED** [review]

**Review by christindbose — COMMENTED** [review]
Are we still allowed to use printf() in the instrument functions?

The following is from the NVbit release. 

NVBit tools can no longer use syscalls in instrument functions, therefore printf() and assert() are no longer allowed in the injected functions

**Comment by barnes88** [comment]
@christindbose I believe that is only referring to inside the injected function `instrument_inst`. You can confirm this is the case because they have `assert()` and `printf()` calls in the mem_trace.cu tool they release as an example with nvbit 1.7

**Review by christindbose — APPROVED** [review]
ok, LGTM

**Pull request merged**
