### PR TITLE
A couple bugs that cropped up on the Jenkins restart

### PR DESCRIPTION
**Pull request by tgrogers**
Fixing a file naming error that was affecting the PTX job status and stat collection readings.
Also changed the monitor script initiation to actually fail if there are errors with the small tests.

### CODE REVIEW

**Comment by FJShen** [comment]
A couple of Jenkins issues still persist and look quite serious ⚠. 
1. We still have problems with path names. Go to this link [https://tgrogers-pc01.ecn.purdue.edu/job/accel-sim-tracer/job/accel-sim-framework/view/change-requests/job/PR-270/1/consoleText](https://tgrogers-pc01.ecn.purdue.edu/job/accel-sim-tracer/job/accel-sim-framework/view/change-requests/job/PR-270/1/consoleText) - it is the raw text log of this CI test - and search for the string `/racer_accel-sim-`. 
2. The link for the status of the CI test from this Github pull request page to our Jenkins server is not working (if you click on the "details" button after the "`continuous-integration/jenkins/pr-merge — This commit looks good`" item)
3. Related to the previous point: strangely, I found the CI test status for this PR at this URL: [https://tgrogers-pc01.ecn.purdue.edu/job/accel-sim-tracer/job/accel-sim-framework/view/change-requests/job/PR-270/](https://tgrogers-pc01.ecn.purdue.edu/job/accel-sim-tracer/job/accel-sim-framework/view/change-requests/job/PR-270/) Note that this PR is under the path of "Dashboard > **accel-sim-tracer** > accel-sim-framework > Pull Requests (11) > PR-270" on our Jenkins server webpage. 
4. According to the log of the Jenkins CI test for this PR, PTX was not tested. I reached this conclusion by searching for "QV100-PTX" and not finding a hit in the raw log file.

**Review by FJShen — CHANGES_REQUESTED** [review]
Please see my comments above

**Comment by tgrogers** [comment]
@FJShen - thanks for the quick look and engaged reply.
Let's handle these things this way:

1) Please approve if everything is fine with this fix (i.e., it is pure goodness, not all the goodness we want, but goodness nonetheless).
2) Take each line item of stuff that is broken, create an issue, and assign it to me.

We should aim at making continuous progress in small increments, rather than forcing giant PRs that fix the world.

**Review by FJShen — APPROVED** [review]

**Comment by FJShen** [comment]
Looks like pure goodness after all.

**Pull request merged**
