### PR TITLE
Add Weekly tests 

### PR DESCRIPTION
**Pull request by JRPan**
Weekly test that correlates everything if there is any new commit to either the frontend/backend.

But for now, only Rodinia-3.1 and ubench. The rest are not working. We need to test out each of the applications. 
I will fix that in a future PR. 

3 stages:
1. Check for change files
2. if the tracer is updated - remove old traces and re-trace everything
3. then run simulations using the traces.

### CODE REVIEW

**Comment by JRPan** [comment]
And ignore the commit names. It will be squashed.

**Review by cesar-avalos3 — APPROVED** [review]
lgtm

**Comment by christindbose** [comment]
LGTM

**Review by christindbose — APPROVED** [review]
LGTM

**Pull request merged**
